<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[HOME PAGE DISPLAYED]]>
    </line>
    <line>
      <![CDATA[LOGIN PAGE DISPLAYED]]>
    </line>
    <line>
      <![CDATA[HOME PAGE DISPLAYED]]>
    </line>
    <line>
      <![CDATA[LOGIN PAGE DISPLAYED]]>
    </line>
  </reporter-output>
  <suite started-at="2023-04-11T16:56:21 IST" name="Suite" finished-at="2023-04-11T16:56:47 IST" duration-ms="25729">
    <groups>
    </groups>
    <test started-at="2023-04-11T16:56:21 IST" name="Test" finished-at="2023-04-11T16:56:47 IST" duration-ms="25729">
      <class name="com.demowebshop.automation.testscripts.TS_login">
        <test-method is-config="true" signature="openapp(long)[pri:0, instance:com.demowebshop.automation.testscripts.TS_login@57af006c]" started-at="2023-04-11T16:56:22 IST" name="openapp" finished-at="2023-04-11T16:56:27 IST" duration-ms="5441" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method signature="loginscript(java.lang.String,java.lang.String)[pri:0, instance:com.demowebshop.automation.testscripts.TS_login@57af006c]" started-at="2023-04-11T16:56:27 IST" name="loginscript" data-provider="usercred" finished-at="2023-04-11T16:56:34 IST" duration-ms="6731" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[hello]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[world@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Please enter a valid email address] but found [Please enter a valid email address.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please enter a valid email address] but found [Please enter a valid email address.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.demowebshop.automation.testscripts.TS_login.loginscript(TS_login.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HOME PAGE DISPLAYED]]>
            </line>
            <line>
              <![CDATA[LOGIN PAGE DISPLAYED]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginscript -->
        <test-method is-config="true" signature="closeapp()[pri:0, instance:com.demowebshop.automation.testscripts.TS_login@57af006c]" started-at="2023-04-11T16:56:34 IST" name="closeapp" finished-at="2023-04-11T16:56:35 IST" duration-ms="699" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeapp -->
        <test-method is-config="true" signature="openapp(long)[pri:0, instance:com.demowebshop.automation.testscripts.TS_login@57af006c]" started-at="2023-04-11T16:56:35 IST" name="openapp" finished-at="2023-04-11T16:56:39 IST" duration-ms="4806" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method signature="loginscript(java.lang.String,java.lang.String)[pri:0, instance:com.demowebshop.automation.testscripts.TS_login@57af006c]" started-at="2023-04-11T16:56:39 IST" name="loginscript" data-provider="usercred" finished-at="2023-04-11T16:56:46 IST" duration-ms="6598" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[world]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hello@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Please enter a valid email address] but found [Please enter a valid email address.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please enter a valid email address] but found [Please enter a valid email address.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.demowebshop.automation.testscripts.TS_login.loginscript(TS_login.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HOME PAGE DISPLAYED]]>
            </line>
            <line>
              <![CDATA[LOGIN PAGE DISPLAYED]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginscript -->
        <test-method is-config="true" signature="closeapp()[pri:0, instance:com.demowebshop.automation.testscripts.TS_login@57af006c]" started-at="2023-04-11T16:56:46 IST" name="closeapp" finished-at="2023-04-11T16:56:47 IST" duration-ms="664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeapp -->
      </class> <!-- com.demowebshop.automation.testscripts.TS_login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
